server:
  port: 8083

spring:
  application:
    name: REDIRECT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortenerdb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.security: DEBUG
    org.url.shortener: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka