server:
  port: 8084

spring:
  application:
    name: ANALYTICS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortenerdb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 789b6435dd3f4d8033e2f539e90975bbb4affe3d4d53d9d3ca1cbfbcf23e309bfaecc77147ecf75c4b6c1ebaee9496f117426f268749a7a1f3b673f7b9d44cfd
  expiration: 172800000

logging:
  level:
    org.springframework.security: DEBUG
    org.url.analytics: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka